<a href="https://colab.research.google.com/github/raapassos/DataScience/blob/main/Projeto_Lojas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando os dados

In [6]:
import pandas as pd
vendas = "/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx"
tabela_vendas = pd.read_excel(vendas)
display(tabela_vendas)

        Código Venda       Data  ... Valor Unitário Valor Final
0                  1 2019-01-01  ...            358         358
1                  1 2019-01-01  ...            180         360
2                  1 2019-01-01  ...            368         368
3                  2 2019-01-02  ...            200         600
4                  2 2019-01-02  ...             71          71
...              ...        ...  ...            ...         ...
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[100999 rows x 7 columns]

Faturamento

In [7]:
faturamento = tabela_vendas[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
faturamento.head()

                            Valor Final
ID Loja
Bourbon Shopping SP             1726110
Center Shopping Uberlândia      1668921
Iguatemi Campinas               1762419
Iguatemi Esplanada              1699681
Norte Shopping                  1711968

In [8]:
faturamento = faturamento.sort_values(by='Valor Final', ascending = False)
display(faturamento)

                                  Valor Final
ID Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

Quantidade Vendida

In [9]:
quantidade = tabela_vendas[['ID Loja', 'Quantidade']].groupby('ID Loja').sum()
quantidade.head()

                            Quantidade
ID Loja
Bourbon Shopping SP               8863
Center Shopping Uberlândia        8627
Iguatemi Campinas                 8935
Iguatemi Esplanada                8580
Norte Shopping                    9014

In [10]:
quantidade = quantidade.sort_values(by='ID Loja', ascending = False)
display(quantidade)

                                  Quantidade
ID Loja
Shopping Vila Velha                     9224
Shopping União de Osasco                8730
Shopping SP Market                      8927
Shopping Recife                         8581
Shopping Morumbi                        8508
Shopping Midway Mall                    8206
Shopping Iguatemi Fortaleza             8629
Shopping Ibirapuera                     8723
Shopping Eldorado                       8719
Shopping Center Leste Aricanduva        8938
Shopping Center Interlagos              8675
Shopping Barra                          8638
Salvador Shopping                       8698
Rio Mar Shopping Fortaleza              8937
Rio Mar Recife                          8863
Ribeirão Shopping                       8825
Passei das Águas Shopping               8618
Parque Dom Pedro Shopping               8388
Palladium Shopping Curitiba             9091
Novo Shopping Ribeirão Preto            8751
Norte Shopping                          9014
Iguatemi Esplanada                      8580
Iguatemi Campinas                       8935
Center Shopping Uberlândia              8627
Bourbon Shopping SP                     8863

Ticket Médio

In [11]:
ticket_medio = (faturamento['Valor Final']/quantidade['Quantidade']).to_frame()
ticket_medio = ticket_medio.rename(columns={0: 'Ticket Medio'})
ticket_medio.head()

                            Ticket Medio
ID Loja
Bourbon Shopping SP           194.754598
Center Shopping Uberlândia    193.453228
Iguatemi Campinas             197.248909
Iguatemi Esplanada            198.098019
Norte Shopping                189.923231

In [12]:
ticket_medio = ticket_medio.sort_values(by='Ticket Medio', ascending=False)
display(ticket_medio)

                                  Ticket Medio
ID Loja
Iguatemi Esplanada                  198.098019
Iguatemi Campinas                   197.248909
Bourbon Shopping SP                 194.754598
Parque Dom Pedro Shopping           194.519552
Rio Mar Recife                      194.377299
Shopping Iguatemi Fortaleza         194.092479
Shopping Midway Mall                193.814404
Center Shopping Uberlândia          193.453228
Ribeirão Shopping                   193.441586
Shopping SP Market                  192.871401
Novo Shopping Ribeirão Preto        191.775226
Shopping Barra                      191.375666
Passei das Águas Shopping           191.345324
Shopping União de Osasco            190.580756
Rio Mar Shopping Fortaleza          190.044758
Norte Shopping                      189.923231
Shopping Recife                     189.357767
Salvador Shopping                   189.323868
Palladium Shopping Curitiba         189.321307
Shopping Center Interlagos          189.105014
Shopping Eldorado                   189.025232
Shopping Center Leste Aricanduva    188.282614
Shopping Vila Velha                 187.680724
Shopping Ibirapuera                 187.442394
Shopping Morumbi                    186.464974

Função Enviar E-mail

In [20]:
def enviar_email(nome_loja, tabela):
  import smtplib
  import email.message
  server = smtplib.SMTP('smtp.gmail.com:587')  
  corpo_email = f"""
  <p>Prezados,</p>
  <p>Segue relatório de vendas</p>
  {tabela.to_html()}
  <p>Qualquer dúvida estou à disposição</p>
  """
    
  msg = email.message.Message()
  msg['Subject'] = f"Relatório de Vendas - {nome_loja}"
  msg['From'] = 'raissa.padial@gmail.com'
  msg['To'] = 'raissa.padial@gmail.com'
  password = "383967739DARA"
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(corpo_email )
    
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

Enviar o E-mail

In [23]:
tabela_completa = faturamento.join(quantidade).join(ticket_medio)
enviar_email("Diretoria", tabela_completa)

Email enviado

Enviar o e-mail para cada loja

In [26]:
lista_lojas = tabela_vendas["ID Loja"].unique()

for loja in lista_lojas:
  tabela_loja = tabela_vendas.loc[tabela_vendas["ID Loja"] == loja,["ID Loja", "Quantidade", "Valor Final"]]
  tabela_loja = tabela_loja.groupby("ID Loja").sum()
  tabela_loja["Ticket Medio"] = tabela_loja["Valor Final"] / tabela_loja["Quantidade"] 
  enviar_email(loja,tabela_loja)

Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado
Email enviado